version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspaces/epicenter:cached
      - devcontainer-node-modules:/workspaces/epicenter/node_modules
    command: sleep infinity
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://epicenter:epicenter@postgres:5432/epicenter

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: epicenter
      POSTGRES_USER: epicenter
      POSTGRES_PASSWORD: epicenter
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U epicenter -d epicenter"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  devcontainer-node-modules: